# Generated by Django 4.2.2 on 2023-07-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessride', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='defect',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
