# Generated by Django 4.2.2 on 2023-07-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessride', '0002_detail_defect'),
    ]

    operations = [
        migrations.CreateModel(
            name='driverdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_image', models.ImageField(upload_to='photo')),
                ('driver_address', models.TextField()),
                ('driver_phoneno', models.BigIntegerField()),
                ('driver_licenseno', models.CharField()),
                ('driver_licenseimage', models.ImageField(upload_to='Verification')),
            ],
        ),
    ]
