# Generated by Django 4.2.2 on 2023-07-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessride', '0003_driverdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdetail',
            name='driver_demo',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
