# Generated by Django 4.2.2 on 2023-07-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessride', '0004_driverdetail_driver_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdetail',
            name='driver_reason',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
