# Generated by Django 4.2.2 on 2023-07-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessride', '0005_driverdetail_driver_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='mode_of_ride',
            field=models.CharField(choices=[('Two Wheeler', 'Two Wheeler'), ('Four Wheeler', 'Four Wheeler')], default=0, max_length=50),
            preserve_default=False,
        ),
    ]
