# Generated by Django 4.2.2 on 2023-07-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessride', '0008_detail_passenger_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='Gender',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detail',
            name='passenger_feedback',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
