# Generated by Django 4.2.2 on 2023-07-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessride', '0009_detail_gender_alter_detail_passenger_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdetail',
            name='Gender',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
