# Generated by Django 4.2.2 on 2023-07-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessride', '0010_driverdetail_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverdetail',
            name='Gender',
        ),
        migrations.AddField(
            model_name='driverdetail',
            name='driver_training',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
