# Generated by Django 4.2.2 on 2023-07-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessride', '0011_remove_driverdetail_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdetail',
            name='driver_vehicle_accessible',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
