# Generated by Django 4.2.2 on 2023-07-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessride', '0013_driverdetail_past_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdetail',
            name='driver_attitude',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
