# Generated by Django 4.2.2 on 2023-07-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessride', '0015_driverdetail_driver_physical_ability'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdetail',
            name='Gender',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
